services:
  web-dev:
    container_name: react-nextjs
    tty: true
    stdin_open: true
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
    profiles:
      - dev
      - ''
  web-prod:
    container_name: react-nextjs
    tty: true
    stdin_open: true
    build: 
      context: .
      target: production
    ports:
      - "3000:3000"
    profiles:
      - prod

networks:
  default:
    name: react-nextjs
    driver: bridge